[project]
name = "SEG_514143"
version = "0.1.0"
description = "PA228 course segmentation project"
authors = [
    {name = "Matěj Kubík", email = "matej.kubik@mail.muni.cz"},
]
dependencies = [
    "graphviz",
    "matplotlib",
    "numpy",
    "pillow",
    "torch",
    "torchview",
    "pandas",
    "albumentations",
    "tqdm",
    "torchvision",
    "mlflow",
    "types-tqdm>=4.67.3.20260408",
]
requires-python = "==3.14.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.pdm.scripts]
train = "python training.py data_seg_public"
mlflow = "mlflow server --host 127.0.0.1 --port 5000"